# -*- coding: utf-8 -*-
"""Example_01_How_to_extract_the_metric

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-NSt7EbAVtGGjUBZ50iqkDiW_E8-XqY
"""

"""
Course title: AlgoMania
Instructor: Thiago Brito - Universo DEV
Example adapted by: Charles Fernandes de Souza
Date: September 23, 2024
"""

def find_sum(my_array):
    total_sum = 0
    for item in my_array:
        total_sum += item
    return total_sum

def main():
    my_array = [10, 20, 30, 40]
    result = find_sum(my_array)
    print(f"The sum of the array elements is: {result}")
main()