# -*- coding: utf-8 -*-
"""example_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xUuyz23ZTvOi-8Zt8DUuhiCVSXN_4gy
"""

"""
Course title: AlgoMania
Instructor: Thiago Brito - Universo DEV
Example adapted by: Charles Fernandes de Souza
Date: September 27, 2024
"""
def find_max(my_array):
  max = 0
  for item in my_array:
    if item > max:
      max = item
  return max

def main():
  my_array = [10,20,30,40]
  result = find_max(my_array)
  print(result)
main()