# -*- coding: utf-8 -*-
"""example_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQ8CtzNwKCgURJRfeg6c1g9DS537U5Ry
"""

"""
Course title: AlgoMania
Instructor: Thiago Brito - Universo DEV
Example adapted by: Charles Fernandes de Souza
Date: September 27, 2024
"""
def print_items(my_array):
  for item in my_array:
        # Since it iterates through all elements once, the loop runs 'n' times,
        # where 'n' is the size of the array.
    print(item)

def main():
  print_items(my_array = [10,20,30,40])
main()