# -*- coding: utf-8 -*-
"""example_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ppCK2__61OV_QLlJaOkC53RSwPXIHmGP
"""

def factorial(max_number):
    # Initiates a loop that will traverse from 0 up to max_number-1
    for each in range(max_number):
        print(each)
        # Recursively calls the factorial function, decreasing the max_number by 1 each time
        # This recursive call generates factorial growth (O(n!)) due to the nature of multiple recursive invocations
        factorial(max_number - 1)

factorial(3)