# -*- coding: utf-8 -*-
"""Example_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PFSx29TDak5TrBY5WmiBSZONzv2FvimG
"""

"""
Course title: AlgoMania
Instructor: Thiago Brito - Universo DEV
Example adapted by: Charles Fernandes de Souza
Date: September 26, 2024
"""

def example_1():
  """
  The following line has a time complexity of O(1) because it performs a single operation (printing)
  regardless of the size of the input or any other variable factors.
  """
  print('hello world')
example_1()