# -*- coding: utf-8 -*-
"""Example_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIz1uZylld_KqKteyda_SBNzACZVYf9B
"""

"""
Course title: AlgoMania
Instructor: Thiago Brito - Universo DEV
Example adapted by: Charles Fernandes de Souza
Date: September 26, 2024
"""

def example_2(n):
  """
  This method takes an integer n and returns it.
  The time complexity is O(1) because the method performs a single operation,
  regardless of the size or value of n. It always takes the same amount of time to execute.
  """
  return n
example_2(1)