# -*- coding: utf-8 -*-
"""example_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Oc2gLqk7jytoqMmcdqeSsC-oz3ZK922
"""

def find_common_elements(my_array01, my_array02):
  result = []

  for item01 in my_array01:
    for item02 in my_array02:
      if item01 == item02:
        result.append(item01)
  return result

my_array01 = [10, 20, 30, 40]
my_array02 = [50, 20, 30, 80]

common_elements = find_common_elements(my_array01, my_array02)
print(common_elements)