# -*- coding: utf-8 -*-
"""example_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhrEiD8Cf8VTXkUAo52hB1MhrZS4vKY1
"""

def bubble_sort(my_array):
    n = len(my_array)
    # First iteration over the list (O(n))
    for i in range(n):
        # Second iteration for comparisons (O(n - i - 1)) ≈ O(n)
        for j in range(0, n - i - 1):
            # Comparison and swapping elements if needed
            if my_array[j] > my_array[j + 1]:
                my_array[j], my_array[j + 1] = my_array[j + 1], my_array[j]  # Swap elements
    return my_array


my_array = [30, 40, 20, 10]
sorted_array = bubble_sort(my_array)
sorted_array