# -*- coding: utf-8 -*-
"""example

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9oBy7YtQk-_OPQF2lHwVSRGGPWjuqS_
"""

def binary_search(my_array, item):
    lower_bound = 0
    upper_bound = len(my_array) - 1

    while lower_bound <= upper_bound:
        middle_index = (lower_bound + upper_bound) // 2 # It divides the search space in half with each iteration, effectively reducing the search time logarithmically O(log n)
        guess = my_array[middle_index]

        if guess == item:
            return middle_index
        elif guess > item:
            upper_bound = middle_index - 1
        else:
            lower_bound = middle_index + 1

    return None  #

my_array = [10, 20, 30, 40]
print(binary_search(my_array, 30))