# -*- coding: utf-8 -*-
"""Example_04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117eCpxiGIpW5aX3m00GTng6nRkSMshNp
"""

"""
Course title: AlgoMania
Instructor: Thiago Brito - Universo DEV
Example adapted by: Charles Fernandes de Souza
Date: September 26, 2024
"""
import queue
def example_04():
    my_queue = queue.Queue()
    my_queue.put(1)
    my_queue.put(2)
    my_queue.put(3)
    # The size() method is O(1) (constant time) because it returns
    # the number of elements in the queue without needing to
    # traverse the entire data structure.
    print("Size of the queue:", my_queue.qsize())
example_04()